name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
    - uses: golangci/golangci-lint-action@v6
      with:
        args: "--out-format=colored-line-number --timeout=10m"
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
    - run: go build -o buildx-telemetry ./cmd
    - run: go test -v ./...
