name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true
    - run: go build -o buildx-telemetry ./cmd
    - uses: golangci/golangci-lint-action@v6
      with:
        args: "--out-format=colored-line-number --timeout=10m"
